package final13febrero026;

public class App {}

//  ELEMENTO COMPOSITE .
    //TITULO STRING
    //FECHA LOCAL DATE
    //GET CANTFOTOS
    //GET TAMANIO
    //GET LISTA PERSONAS
    //COPIA PROFUNDA INCLUYE ALBUM SINO ES NULL
    //BUSCARPRIEMRFOTO
    //buscar
// FOTOGRAFIA SIMPLE
    // IDENTIFICADOR ID.
    // TITULO STRING hereda . 
    // TAMANIO INT.
    // LISTA DE PERSONAS ARRAYLIST STRING.
    //FECHA hereda . 
    //CANT FOTOS.
    //GET TAMANIO.
    //GET LISTA PERSONAS.
    //BUSCARPRIMERFOTO.
    //buscar.

// ALBUM COMPUESTO
    //TITULO STRING.
    //FECHA LOCALDATE .
    //LISTA DE ELEMENTOS ORDENADA (PRIMERO POR FECHA LUEGO POR TAMANIO) ARRAYLISTELEMENTOS.
    //CANT FOTOS.
    //GET TAMANIO.
    //GET LISTA PERSONAS.
    //BUSCARPRIMERFOTO
    // buscar

//REQUISITOS
//CONTAR CANTIDAD DE FOTOGRAFIAS.
//TAMANIO TOTAL.
//ALBUM MIRAMAR 2025 NI IDEA
//LISTADO DE PERSONAS SIN REPETIR
//COPIA DE ALBUMNES

//CONDICIONES interfaz .
// CONDICION PERSONAS
// CONDICION TAMANIO
// CONDICION FECHA
// CONDICION AND .
// CONDICION OR .
// CONDICION NOT .

//COMPARADORES
// SOLO 1, COMPARAR POR FECHA SI ES ==0 COMPARAR POR TAMANIO
